### ISSUE TITLE
How to use command?

### ISSUE THREAD

**Issue by sahvinay** [lazuardyk/Remote-PC-Telegram#1]
I have install and run successfully but where to type the command to get the list of all the available command in telegram?

**Comment by lazuardyk** [comment]
you can type "hi" or "/start" in the chat between you and your chatbot, and your chatbot will respond the available command.

**Comment by sahvinay** [comment]
That I understood but I don't understand who is chat bot, I also search with that name in telegram but didn't find anything. I only know botfather which don't understand this.
After running python setup.py in CMD what will be the exact step on telegram mobile app.

**Comment by lazuardyk** [comment]
First, you must create your own chat bot with BotFather and get your token for your chat bot. *You can read here: https://www.siteguarding.com/en/how-to-get-telegram-bot-api-token. After having your token, you can read instructions to fill the required data on setup.py.
